name:etl pipeline
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print message
        run: echo "Hello, World!"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print message
        run: echo "Hello, World!"
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print message
        run: echo "Hello, World!"
  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print message
        run: echo "Hello, World!"
  job5:
    runs-on: ubuntu-latest
    needs: job4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print message
        run: echo "Hello, World!"
  job6:
    runs-on: ubuntu-latest
    needs: [job4, job5]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: print message
        run: echo "Hello, World!"
